services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=next-step-recommendations-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=next-step'
    ports:
      - ':6543:6543'
